@baseUrl = http://localhost:4000
###

###
@saleId = 6a3143ad-0431-41bd-b2b1-fc294704cac8
###

###
####################### SALES ######################
###

### CRIAR VENDAS
POST {{baseUrl}}/sales
Content-Type: application/json

{
  "userId": "46f4b62c-963f-42bb-97cf-7cd00a023b27",
  "eventId": "3d74a3fb-34b2-42da-bbc9-575f0972e316"
}

###

###
### BUSCAR VENDAS
GET {{baseUrl}}/sales

###

###
### BUSCAR POR ID
GET {{baseUrl}}/sales/{{saleId}}

###

### ATUALIZAR STATUS (SIMULAR PAGAMENTO)
PUT {{baseUrl}}/sales/{{saleId}}
Content-Type: application/json

{
  "status": "PAGO"
}

###

### CANCELAR VENDA
PUT {{baseUrl}}/sales/{{saleId}}
Content-Type: application/json

{
  "status": "CANCELADO"
}

###

### ESTORNAR VENDA
PUT {{baseUrl}}/sales/{{saleId}}
Content-Type: application/json

{
  "status": "ESTORNADO"
}

###

### DELETAR VENDA
DELETE {{baseUrl}}/sales/{{saleId}}

###