spring.application.name=gateway

# Porta do servidor
server.port=8080

# Configurações do Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Endereço frontend - aplicação web
gateway.frontend.uri=http://localhost:5173

# Exemplo de configuração a partir da variável de ambiente do sistema operacional
gateway.frontend.token={GATEWAY_FRONTEND_TOKEN}