@urlServer = http://localhost:3000
###
GET {{urlServer}}//users/status
###
GET {{urlServer}}//ccn
###
POST {{urlServer}}//ccn
Content-Type: application/json

{
  "name": "Mastercard"
}

###
GET {{urlServer}}/users

###
POST {{urlServer}}/users
Content-Type: application/json

{
  "name": "Fernando",

  "creditCardNetworkId": "4b86bb86-0ad7-4c34-acc0-70fd333f53f8"
}